drlop table if exsists users;

CREATE TABLE users(
  id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email   text NOT NULL UNIQUE,
  nume    text NOT NULL UNIQUE,
  password text,
  avatar  text,
  profile text, -- admin, user, 
);


insert into users (nume, email, password) values ('radu Lodina', 'rlodina@gmail.com');


